import { StyleSheet } from "react-native";

export default StyleSheet.create({
  containerPrincipal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    padding: 10,
  },
  containerRotas: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  containerFormulario: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  containerConteudos: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 15,
  },
  containerDado: {
    borderRadius: 10,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "#5252DF",
    margin: 5,
    padding: 10,
  },
  tituloPrincipal: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    textAlign: 'center',
  },
  text: {
    fontSize: 19,
    margin: 3,
    textAlign: 'center',
    color: '#fff'
  },
  tituloTerciario: {
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 5,
    textAlign: "center",
  },
  botao: {
    paddingVertical: 13,
    paddingHorizontal: 21,
    backgroundColor: '#5252DF',
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    marginTop: 5,
    marginBottom: 10,
  },
  textInput: {
    height: 45,
    width: 320,
    color: '#fff',
    borderColor: '#5252DF',
    borderWidth: 3,
    borderRadius: 25,
    paddingHorizontal: 17,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 3,
  },
  card: {
    backgroundColor: "#373B35",
    padding: 8,
    borderRadius: 15,
    marginTop: 24,
    borderWidth: 4,
    borderStyle: "solid",
    borderColor: "#5252DF",
  }
})